language: ruby
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:setup --trace
  - bundle exec rake db:test:prepare --trace
after_script:
rvm:
  - 2.2.3
script:
  - bundle exec rspec
addons:
  postgresql: "9.3"
  code_climate:
    repo_token: 299bc11317f37393fbd2a18d68ab95fe0bd9b8d0231bfad73d7b4187141c7abd
